# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12569520487c1135972be187498c2513b9724917a04c2f52d1c122c1cf8b3e3816a58ef64a506fb993f96d634c0c8e781d2d692e4403f0c8ca11105c59b4a057
  comic_vine_key: <%= ENV["COMICVINE_PRIVATE"] %>

test:
  secret_key_base: ae9a61f1fe03c96edb9daac96676cd01df1526f2491dcb7bf6358ed88cbd23de14d261d542ac5ed08d575397c3288f886086419fe863a83c0070dda22780172d
  comic_vine_key: <%= ENV["COMICVINE_PRIVATE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  comic_vine_key: <%= ENV["COMICVINE_PRIVATE"] %>
